version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5438"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_api
